kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:ufgyP61XobxjgnCbEFDJQcmQhuQ+dmUd6PF9Fot91c6sZXhVd40cDq71/X0yRePmvHDMFRcv2QGvHnTgMjMFT6IgHyU=,iv:gZcTgbOccZJlsDCwD2WU+pQb3qvV2T0Zl8gly8A1BHk=,tag:I9sTNCmZ+iTowdqziJly6A==,type:str]
    github_user: ENC[AES256_GCM,data:/NMJdiH/0E3dy0DbsDlOgxZj2Xs=,iv:aG/vAAMGvkpFDveSFNNDwOrkw2Fl/6WtpEg7S0Qs5C0=,tag:z01nzHmpG1x11TAq0bMkKg==,type:str]
    github_api_token: ENC[AES256_GCM,data:fn8Zrpmmr26YVy530vBPavJ+zRKwP8OVzhOGCpyPAK4E25faaIInzw==,iv:Wnzzpm4b9sQU5fLb1/0g9vc6fnGBGyWZtz+ZMX0AsRs=,tag:MaNMfpG0F6MpzniQcVCh+Q==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:hvT2JK6nV2n3,iv:U+CpOKyXdI+/np/HUgGftSldq/s9jdlWnZ91TSSsQjg=,tag:6kHnB2m7JBstEOwf8MXVbw==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:2tI0AooPRq9d,iv:8tm9xerrwzKAirn4rp1/nqv905EbVkqyX8vJVyB/H6w=,tag:PGSEYW8LRcsR+KV/q8sgGg==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:nxSVolWWuXYB7KKANw==,iv:3z0Lwu/q+T+Ome/YVxSE8WWEzwU4ThBLz2UlsN2aRhM=,tag:EWBNGKrqF7aZ08ELgU3ucA==,type:str]
    prism_central_user: ENC[AES256_GCM,data:1h6pz5I=,iv:rFTHzpDRq3yOZvTVA0W6c20I361/M912rqgOZYsySEM=,tag:T+2rRpRn1lQ5ALOg9kbDWA==,type:str]
    prism_central_password: ENC[AES256_GCM,data:IPuVHpB+z9ja4RM=,iv:Vc/IL1uUszI5F52X4vaogqF5miVkfPq3kQhrqSAFWWc=,tag:V7+XKUI47XFrXp8dyc73ww==,type:str]
    objects_host: ENC[AES256_GCM,data:MPh+5Sxpr8LcAUpp5CA=,iv:EvhEq4FCGpZC/HP+OD2ji2sD5nGwZUU01YyCT1Wh0zY=,tag:13XqIINj2psPeAR/n69LGA==,type:str]
    objects_port: ENC[AES256_GCM,data:5zU=,iv:dOECyH3+JDfLsMy9QUvemwaDTnwPSgzVYrJorF0ERmo=,tag:F/UmRdcZEPTAd4ETTBTFbA==,type:str]
    objects_region: ENC[AES256_GCM,data:IEXsVhLL6G1s,iv:Hd3jyJq6XaLl7LeP3C9pjL9ckraVQPQrxQoEVlTIdE4=,tag:CbqqXSpnJViN/VcIYdTN/Q==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:5JH1oAM=,iv:sfzVXKjQjEkRmDnp7Ta26mNZGmgOSOKuAN4CSMcnZGY=,tag:pgRWWOjl8MdY47930+ySPQ==,type:str]
    objects_access_key: ENC[AES256_GCM,data:2+kfmclakzV26tYCOhT3ayR72Cw06yUS02ZM9r12go8=,iv:Wwu6vCRKQ6e9MyZFG1vXin/bLSS/C0Uw+AcHJOkFqI4=,tag:cdmkP/ohxvONImsz6bUhpg==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:/potbskYb6SBjVdWygJwQ9g1uszAt5AHAJ3gvLpXGGA=,iv:pguxtcwPnar1S0PQWtMSj4pnqunNGzPXeqC2b0zQ79s=,tag:PrviVByItGdluBXnvc5mNQ==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:FeKWH2bVJ0jZuEMLvqiDsHT42192VC3OWBQ5Gok=,iv:YubGfmLIP7Br3/v5CNTlmBfmAA0H3G6PLykksToYtgU=,tag:+LluG2i++wDn4eNTAGGhWg==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:TOwKCtNLhHLo82ljH6tPvhM=,iv:I3ItGv+FW15u3KF4jNA4NggIucfgMzrb9Yzdj90x1f0=,tag:dUMASWbGKOWFgUn6rI9ktA==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:weM2wzs3nk5/8JcZIF1FipTn/jurmWj+9YUg7dlVY3WRkw==,iv:bOlCo/g44o/BsDlSI9rsxJyr7LDcmACboOTVhJZ6hq0=,tag:tyJLGGHQ7KFJqUpcxChqxg==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:R9AXHQKhb0UfRzL348kRYazVLhXHp0W/kK5giTsTXcAceQ==,iv:yXiTglg5HlaMfq3PTjwcBjJuRyGG6Fd96BGUdWaF/Yg=,tag:cWV8Msx8rJzR/sKiNHHzOQ==,type:str]
    weave_gitops_default_pass: ENC[AES256_GCM,data:cSgHdC4O2L/KBOLFO05V+O4y0EajbgzDaFAFD0iQYFPBkkX+2pYZcb0qky6ggGMZ9kUlDuQEqoYfz2ft,iv:smwvFaPahn1035Vqc7s1xQ9ZBnWgZdJncGDSmEuvp+4=,tag:6fAwl05xcsezRlrhUy+5Ug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u4atkamfwfp46r8xqd2c0a778nss242fuvw8ar5fkfx226er2ujsn6p2np
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwekVPa2N1MjhqamNUZzNm
            eFFNLzk0YkgrVGhhcllvQWt2NW9SdGxIM3pJCjBkVDd0WGl6Vkh0YVJFVm9JMEJR
            S2FPSDhUYTU2RnZxUHRMZWYzdUREdW8KLS0tIDRIRGRidGlzY095YmNUUmpLK2hv
            N296M1dtSTAvSE1TNWxlNER3N0t4WkEKQvc4RAPLJspo/GgSAf1muMYIlzEAP9f/
            /fqCRQtckD0p4KVjgMjYUJ51kljRbbZBfQSbX1ACfPmqzpdW0xz/cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-02T10:00:07Z"
    mac: ENC[AES256_GCM,data:WvOyxpCwfU+SOkGIOPEPPdfzoR5FwtkBP+pdDldtzQbWMtM8Z5uDpeOHj+Z/QzmajjIIC9ND8rgKVSXubP3xsyaCrV0THvh88RqByRR0bkMMYdGYahAxymsdBHPH3ruBubZ8yrupDCgDG3v93QNgXsoLZTzUnAbNKgRJ+7XGtUQ=,iv:Cyi3IFJKu9BlYwH2NA/K32XvUdG3HfFeVKk9UELsPrw=,tag:aoqdQJsDXveDM4MmJ4uFsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
