kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:IhXL0DIlWxwPIaDbx2CY7+BZ8xdXJdJiQt1ttcAVLgT9FXvmDzhafT62PiLVibcSvwhRbwhYgi510Nyb0WhoitrOvwo=,iv:hXQesqMOxv22qzG5LendhkWpU7+w7QCwYmvdgQluLvI=,tag:QjUbZ545yJrx6BduA5DLlg==,type:str]
    github_user: ENC[AES256_GCM,data:qocK1jZZJvw=,iv:5oJDBITG6RxSkhIV4qBCjp5i5/RZnItUvKVEA63i7U8=,tag:YuE8v92xQpn3p8wwlzZRag==,type:str]
    github_api_token: ENC[AES256_GCM,data:e8drxztRA6/KYbXL6GcFJ3jOLJjnsIMKoR96GALCboK5ULC+2BN6+w==,iv:grbxi+DoUfOtU5rZ//1WKGfZqToHc6HdnF1GEbMyr+Y=,tag:XtNJAzZEqGXvoz4SY3PU7Q==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:IVYtacdfiy0m,iv:Prcz2WjH8LnzvhHR8FYbM0h6YIEGjhMePLGATJ5shyk=,tag:vMSEIr0ih8QJP9Bf/AC9LQ==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:Npo3YukFFtai,iv:VUhljLpS4941BA1IVf/ykkW+hGlpk/Ob+PWVtP/pfo0=,tag:lM8gTYbmhdX8u+HKI5154w==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:DEWeUvr3WpocRG6LWw==,iv:Oj/HmRmj8TQ8tClXzjRUCZgdcw7I/Gg/rjOG1+/mFvA=,tag:r/kXjxXhgyJnp2PT/x3IWg==,type:str]
    prism_central_user: ENC[AES256_GCM,data:LXGZAU8=,iv:5c1tD3xzOe4zwBshLedBX1+USsgvKj3DC6SS72ococU=,tag:iYjItJ3VJfIgA8ozLkzduw==,type:str]
    prism_central_password: ENC[AES256_GCM,data:vtJHEI4YVo9Dm5c=,iv:ABAZSwNlCeEJRdvBi4JXYzsVdLwkhCMluDtTcl5/m1o=,tag:buE9sDWFtpdPBHLGK7V9zw==,type:str]
    objects_host: ENC[AES256_GCM,data:EmspI0YkkDrtY1H1Njw=,iv:nBpZUOX7anxP7/qJ4NLze+j5sSTxdbLdIfdmj7ipCzE=,tag:FctrIb4nyt+jnPkQQqQaWw==,type:str]
    objects_port: ENC[AES256_GCM,data:7KE=,iv:9DAouIq97qJiFPceHkrraCZn1nYEj4bxdtJKjCRlcVE=,tag:hvgOliqDJdeSw035OR2YUw==,type:str]
    objects_region: ENC[AES256_GCM,data:5L4NQuQ6mj94,iv:918Z5JD6aFu5pMHOB/lI4DdRDUJCM4w8/LS8Dr8MJ9c=,tag:iAs4DxPTdcuQgabjqQF0uQ==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:ibPxn8Q=,iv:xk0sBC9JY4HKw2afk94gNv+jFPTWM8xA7GG6Q1nRVCE=,tag:SAyhZ9BHfsJWMdctRFqycA==,type:str]
    objects_access_key: ENC[AES256_GCM,data:Qeu1k8l+Und1po81qQNwIjvdFBfMKYyUwqZqE4xMSA8=,iv:gaV4nSF+33y/DaYzqMZsrl0WnQOkvWKfosyluu5IWZQ=,tag:Z7MoqmYTZ064hBy5gzlszA==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:y8vvbtKWF74mtOBiOReJa4DqklKos0tKGhEv6hxQwGc=,iv:5tYv8R4O78457puzcvM9JNttccjqIGdnix77zYX/Fno=,tag:57BzR8bEW9rHwFn3GBJvxg==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:yrUrojdf4uRNfXxJV26A2ja56t3GZPY20TqgxPQ=,iv:4tneXW/ZW0QsQGmLtB46LkrbotaL+sUzXneMXoUTZko=,tag:N29rbC9GaFgFDbCwrqBQMA==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:1wzlIxHVjjsXpMM92LgPnJc=,iv:GlWq1+8dCo8Mlfo4NxIF2EVAl1JwNE+zPv26OTr50tg=,tag:pOiqskGJp8RaXsFMTnInrg==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:h/nss14UHZ7CY+2cXnsi5G/FtN7b5T15mVA4Ieyp+WQZTQ==,iv:as92J5EkO7aJWwDZNtczLMB+erZ5CqGMXS6vutgvC/A=,tag:ww9xnY/92h/U4J7N3tZt2w==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:xZsyE7mTuZm8YqDvxV1hcAYDGuZzFC9NvyAEeyqeCGhyLw==,iv:xI26LjKWYEY39jyo9NGgcDc7/xFXakTA1ZvNx0HLa0w=,tag:szXSyIWHiNbD8dCc2bX30A==,type:str]
    weave_gitops_default_pass: ENC[AES256_GCM,data:faHoDhXsoymk7p4Rp0rba/EOjP6jmmjGamo/3ONQwYL5NYq9InpGe7RR/rKQtZg7C37yXFDr67sKwQUI,iv:FmYw87Rm039L1q8uWbymRFLeFQuYtA/gA5q17+q2oXI=,tag:AnGP3fEX28c3laZ2oTxkDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u4atkamfwfp46r8xqd2c0a778nss242fuvw8ar5fkfx226er2ujsn6p2np
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRENNd1pGVHNxVkVvLy80
            a1VydkxDcGR6MU5CbENzT0MwbjBHTEcydFdRCm4xTThNKzNiUjY4c2RzYkdOU210
            ckF5WGN5blJwdkVzV1lwVDBxRFJXOHcKLS0tIEV6UmVzSVFGdTBCV0puZUs1bkdJ
            OHE0REhxUDRPdjFhelRFQ1BPM0c2M0UKtuhR/IxYvQW0ZOOWr7gNowRMJ9/2hZaR
            HEDI1c9FTk2A8VXkYToI0NxzjsX9/K0TiKX7VGe64yhT4iOC9GFQyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-08T07:07:44Z"
    mac: ENC[AES256_GCM,data:aEw3YrLG6+jasaRvO1ewqoyU0mIe9czcx1uYH+d6G+JrHPPFRcfXBRZiohVE1H9Nmmlz84XHzY/srXIrF45twNGl+qw6Wo9teNLcZbFJbbJojjNCVxPIf3bBv1fpLgOqBIF1qMUPOUTISwx3e8ricVpN/fcuE2tlJSY2oRbOvu8=,iv:OcJtTtq6JdmcmcMupbewuTDQM2ka1rpm4GwUqSaxAQM=,tag:juA8feh6bMEtl2qOU2gudQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
