kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:CcwH3nKG9cemKlaHer6fq392IkI2WcfeBaGoguHtNtnZA6ZG9SBbxZ09ZQwLmO9mGBw9u2APkSoSxW2o6v4fAC2RLTM=,iv:QylYjL+b5DjAOYUofuNn7KZIJQWzYpDptmDrEktx4z4=,tag:hf624WtAECwUPsJ49KyHvQ==,type:str]
    github_user: ENC[AES256_GCM,data:NH3Hmv+mkbI=,iv:0skZ1mIreeGvreqqE+z8KJ2p/Hpe1I/atzb8VqKy5rc=,tag:918VRND6XrfAZBhFN6dI3Q==,type:str]
    github_api_token: ENC[AES256_GCM,data:a736MaUhnhJ3nr7BGixBhoCJRbGqUJdAr8eW1kNmXytffpIEmFQXyg==,iv:jyRxlj5OHZN0dkS8BoxjecxIo3MpNnfLE4QmWxo8nT8=,tag:NaUeINUt0vXNWAI2Peu3gg==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:NFalFh/bDnBA,iv:NIWRAWewyghZpushUC16clAyPOqBIJxy8F0PAsORAh0=,tag:KN4WIgAHwkoxsmoFy4TkcA==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:m9C+smw3yIMp,iv:x3QUzdcXonrY/gD4phAEzoOzKXtwkJy++Dxm4ONaetw=,tag:y2JYl4tSNgIdLQdrU/C1QA==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:w+fUam0DB4K4ej2p7Q==,iv:XN9vO3xoORNc9Euwe0/Wmoqd2s3n205emE+7sVfI098=,tag:o1ILl26kGOto3Gf/E4z37w==,type:str]
    prism_central_user: ENC[AES256_GCM,data:BSaEY+M=,iv:cSAJxSwrTeHRbMsrMBB9WtcTP38/xqfzntqkwHiUm5Q=,tag:439iz8x6PLLdfG3bYkk6kA==,type:str]
    prism_central_password: ENC[AES256_GCM,data:I5Pwsje8Y/UDLSY=,iv:hdnjLD3lpOgrG12m9CRghQDPA9Dpqvt/v2NXM0bQWBc=,tag:EKF9rWiJH4+vjKhOBcy4oA==,type:str]
    objects_host: ENC[AES256_GCM,data:offc9dvH3Rd5qs6Xzrk=,iv:JzIgNbq8G6Eu4192DPPaa9KZseNlXTEKUGi63+F/Mys=,tag:f0BZr+khkmXPVzZUTWjeFQ==,type:str]
    objects_port: ENC[AES256_GCM,data:DDI=,iv:NyZcbgGLAXqlG5+iv5UaYEC7rnRPMiVtNYxx+lYYZ18=,tag:HzweeT1sHi1MI5NBH+obBg==,type:str]
    objects_region: ENC[AES256_GCM,data:gNHSMxO7Sz9f,iv:anDjZaAa0eGbBn79OhbcePWohU+ipCSvCRWis6Xd5XI=,tag:fUAIgMbf1P+UH4zZDNBozA==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:r+EyIYs=,iv:w59Xm4eVoZxt61C/MGxn8TXw/2U0o1GkSHay2dlsabo=,tag:duugtPa7p5JvZAYGqOcFEQ==,type:str]
    objects_access_key: ENC[AES256_GCM,data:o2ubWBd9TyrX86BFCnLEn9qls6vXOKS8sX5XjkRK3U8=,iv:IRcydoiM4QWmcrpYxRZe2/wvuJ/gUm2Cp/kqoZEe2/A=,tag:X3C1RTUYKFUlJdUdabnWOQ==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:3KWQqi4t5FFd8/czrwNx0P50N+W/UtjqXfJCc+tzA04=,iv:Gf3UU/uea6CLckBItvm9hw/oQqLvj8EXbgChwQ6I4rA=,tag:UBDn23eJgvIAVuw9NRacRQ==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:JrIPYo6AZWZMf3FeZvMyPjE56LUoxCnCeB0e3XI=,iv:U+tTABHZxhLNUnSVJDT2JnjgQioe/8PFGcX/HWIeSOA=,tag:8k/J85v92onKJF6TTQytAg==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:ImYSQ3zOV2MUdYCi6WEKigQ=,iv:U3SAw9XEfZWt48LI0R8JXgseXlv7HZuqvVozy8+ptIM=,tag:Mxv07lPhHx76s68hyU/iJw==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:uHEVs91tSOIvO9FpDgvimkUSqy8yZWziCX6Y13KA2q3/lQ==,iv:J/qKGSwKzR41nWMbCaFysn5Vo2aeatt9uFTPMB1gd7U=,tag:Y4K6UCS4WUqgFoSdkEeAcQ==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:ax/BrqZn9fCXjWvl0tOXmEnLLkzcvUerZ7ZQ+Pbj6bt3+g==,iv:KsZ2OQCIKBSEQJHr15ym27lMfZHpxnKwx3nuhgk04fQ=,tag:EZ8iOzVNH+bF8qrb/Zt0lw==,type:str]
    weave_gitops_default_pass: ENC[AES256_GCM,data:S/gQ4ClosHIRMWh5jN0N1hQB8+Dc+02YH0tDpnuF6363jibnx0tkhNHnUPax8lLXDkld2GvS0paEZhoX,iv:/suq3p2u7xjObBvbxjX1Na59CDr0ohnDXY6h2F9d1x8=,tag:SiPqS99mwZTAPP1Z3E/aVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u4atkamfwfp46r8xqd2c0a778nss242fuvw8ar5fkfx226er2ujsn6p2np
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Szk0NWlacTBLWTVuWk4z
            NXdPMDJ3eUI2bUhNd0J5MnhvclUveHRwU2g0CklMa1ZPL0RmM0cvZGQxWFQ1ZjFB
            ZFZqUW15UjYvYm9HRDAxWVNOVXV5THMKLS0tIFBUaVFNSkNESWxwMlo3U0hjMFhV
            TE5NdVBybEMzbnpaeHM0dzFHWWljZVEKRUZpI67+lu6Ka5NMg8N78QLsaGFsOm/D
            fgPMiQIHpskGoRYWKWbjtbU3cD0Dh+egi992hHe1giFsk5F+igbvIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-09T09:10:50Z"
    mac: ENC[AES256_GCM,data:jCKpQc5rgZtT8Upz6MJAYj7EjUYYKVT4hdqrSdmQLVdNVUQOs741DVM2QF/R0VGSfGu4Pj0bX52IggbQpYsvnKwzQPUqMBrXwQ8DI/NLLOQaRlJfYrUc+yHlgR2E6gzrCzA86ig1zUZozosIe0GTEWBBg+0BUol5Nq1SmL6aoHg=,iv:fZGTjbYUZ69zqKz0RRt2ehoYj9hRgq8MpKDM21EQ1BQ=,tag:6szZQRSTbawH5v/hJaVQxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
