kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:BzXxB4LbMy7/IRh7huakfsMlycjoo1NKQfM5LF+C18Hmbkhebfu3apGIOuNtGrKq1y6EeCKNz0QuQNORSwgA8s3Yh3A=,iv:ihHJbbwF2yTwO7MQPPfbd1dZ81g9NSaucQb2xgtmEkE=,tag:a2GOpjgC8uHR0utKlosZ2g==,type:str]
    github_user: ENC[AES256_GCM,data:FVw6yPP8siE=,iv:O0+u3fq4hhHb7PPn7dZfJ6qj6c3E1hSTNNi7/cVkwIw=,tag:sZU2CrzYd+KzgJd7sDmvJQ==,type:str]
    github_api_token: ENC[AES256_GCM,data:KmhKsT/o/ebGpSqL0lknaJEXrauvJLnZtjvb51qluBCqbZYs5bh7Ig==,iv:dwMVNELSLJISm+yx9ndW2/gWKkdAOzBQvkZVfGEt+IY=,tag:g6taDxZ8nO7BryTp7M63gQ==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:jqhvY6v2Gtoc,iv:MDDrZFAQbX3ORgTPkA1VkqM6g+W6nkbPckqldutJf68=,tag:QDdsXSXATA0kZg5WDtiLlg==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:topsYlMqYFGD,iv:hxpjsVHxO7+JZmNfTcLYviCdxj/mh3h00fzVZatVOmo=,tag:dsS9IIBKIGiPXuunX7EN0w==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:fEIfvNZruK2l9k6zwA==,iv:efTKTez4HK9cLSUlQpiroaPAu8XN690zbEzQWh4i0lI=,tag:qbvT65plmHGhLRBeH9CWUA==,type:str]
    prism_central_user: ENC[AES256_GCM,data:geyovak=,iv:jm6aKBZpA/IHOff4go9kEZylydxqmJk/l26y3YtncPw=,tag:NgNtbAr3+XkS9/cKxyOlyA==,type:str]
    prism_central_password: ENC[AES256_GCM,data:vw/gXK6N/dm8IU4=,iv:bQW2O+1tdf2SG660vXDompZQYE+vB9+AB0MUGLCOQ6U=,tag:a6VTZeRuGWYEsEKzCG87LA==,type:str]
    objects_host: ENC[AES256_GCM,data:FnnwWki9Ol+tjYo5jHo=,iv:cKV5ppAH+eKgJqB98cJ3L3bneNnxQpeomDF9qo3vH3c=,tag:o8dtnLr5ipq0m/sN9579Ig==,type:str]
    objects_port: ENC[AES256_GCM,data:sXQ=,iv:2NWl9AswsYCleyEuch+M/QeFEQoT2jBPuXIOntDj8OU=,tag:gGnb6Gd8N7JzFvhfrWgopw==,type:str]
    objects_region: ENC[AES256_GCM,data:OZ0Ko1aMNhim,iv:ibuKe0GGtBaMQgfpSbQMR8vLDkQCagqCkdMueI9eK2I=,tag:LOUNNIv/iC99oOkLVVMvQQ==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:82OMkYw=,iv:4h9ZgGMWhlaH3U8X4CoQCnumiJO/oG6USRVSGbkVHWU=,tag:SlZsXZ1JToWerUp2ydolMg==,type:str]
    objects_access_key: ENC[AES256_GCM,data:znCP3cER5YUqiLPkZ6pQKUnd6vPqU9vioS6hvoBdNfc=,iv:4OFktWtKOyGWT4OdM6cT2eGmGVJQYLcb1ARPQh8rBpM=,tag:oPwrKnEkYDutaZ5CnusPLg==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:Gzw1hNvzXGOMWXV82F1gqlafj9M5uTf6aan0zUai0xw=,iv:FfcZlXZyGeGjzqd7LNmo3d9j1VmJExnPDd7BKAopxAA=,tag:Vcr4TU5E+sBAcUcuW5VX5g==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:6glMOjLA3gms6bZiUm4NSd7qU4W4Ffy9I2yBo00=,iv:smL2f2TqkWdszrF6UbIJeb38mmMNKLsU/4nPAxao1Js=,tag:LFSUlQHhyHDkqRGqF0cJAQ==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:cc0qrpj2afO6mwLQ29wq7P8=,iv:z9iNwRdVCVyiLfVlb/OQK3D/AQUKLZx6wXoc3QEmepY=,tag:uHtPgfvYHHVhWhNmHXv1dA==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:/1HZTBaBKvW9YQxPyhf1VXyz3HHLvc3MQ4/vGVLG6xeIJQ==,iv:M1fMqbDTJG9ELRGoE+/xPQkct69LkSYPtmsZmjKTeg0=,tag:bm46lt7d6uuEFQD9y7ISxg==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:2F1P4zhHseQKTKk/vIUg+2PMmr+4geOLbUVDMOSfV6kDwg==,iv:WOlPVP6u0tPR7PukyCdhmz7GSEeQVwJD6k5h8bRQiUA=,tag:WDGVRmqrhP32TF2GZfQtdQ==,type:str]
    weave_gitops_default_pass: ENC[AES256_GCM,data:sH2TWjhQmZft6BEnEZb1T+TSC7N0sS8cKnnGRbH0s1yRpNK3RY4dbZHBywWTwfM5B4ueV0DNnCgxcJNY,iv:dKweHMFnWtZcM9sHNHEyE6svP7xlPDhd2WaLLu6Dtt8=,tag:b9C0HdleLHftfAo3GOieOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u4atkamfwfp46r8xqd2c0a778nss242fuvw8ar5fkfx226er2ujsn6p2np
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQKzd4aHBNMHF6TGowWldY
            MXlKZElDVjFaNkU0Mk04TExjOE0yRlpOVUJJCkIzUzFCMEhKazNaOEZXQXRIMWxk
            bTk4MXhCdFRlRzBVbWpBNW1VMHV4NmcKLS0tIGRXdlFLWUJDMHY1dElPZk0vTUZT
            WVpzcVB6ZTB4c1hTTmcvV0NFQlorSE0KvbNRaDPoKIdPQ0cxXzh1Yb1N/P99i3ZW
            CllXz/1uDg/bC7ktI69uWFnlgM8AIJnm2S+D3lBeKwHYSRhmKcVuxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-08T06:27:20Z"
    mac: ENC[AES256_GCM,data:DelMCbltZvThc9IDrprrpdBRSbGMqkq3I/BRIYIuDLZZFr8oXl4UletGXkDyXGQ9+ODX0My1j962k2Xxhe7TbZ/rTD08Q4oTvA0IQualT3cdqbBY3RecoiQ2FAN5n9UouilfxWn5UdTAVKLFiBNqTfMTrvzegYyrvO5xdBRj/2o=,iv:uyYaUe5lHyejgEYaSYtV9WCvJnwfn8WMg0Nkx0cLSgQ=,tag:Q7VQaIWehdoTGMmfVMkUTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
